In [3]:
import pandas as pd
from pathlib import Path
import numpy as np

In [13]:
ROOT_DIR = Path.cwd()
ss = ROOT_DIR/'data'/'superstoreSales.csv'
df = pd.read_csv(ss, encoding='latin1')

Create a band column ( "high" / "low" by whether Sales > 500) two ways — with apply
and with np.where — and confirm they match.

In [7]:
df['certification'] = np.where(df['Sales'] > 500, 'high', 'low')
df['apply_cert'] = df['Sales'].apply(
    lambda x: 'high' if x>500 else 'low'
)
df

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date,certification,apply_cert
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010,low,low
1,49,293,10/1/2012,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,10/2/2012,high,high
2,50,293,10/1/2012,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-Dï¿½ Ring Binder, Heavy Gauge V...",Small Box,0.39,10/3/2012,low,low
3,80,483,7/10/2011,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,7/12/2011,high,high
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010,low,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,3644,26051,6/27/2010,Not Specified,31,251.7500,0.07,Regular Air,22.46,8.33,...,Northwest Territories,Home Office,Technology,Computer Peripherals,"80 Minute Slim Jewel Case CD-R , 10/Pack - Sta...",Small Pack,0.52,6/28/2010,low,low
228,3649,26116,10/29/2012,Critical,36,697.4100,0.04,Regular Air,81.71,18.97,...,Northwest Territories,Small Business,Office Supplies,Paper,Computer Printout Paper with Letter-Trim Perfo...,Small Box,0.37,10/30/2012,high,high
229,3658,26182,1/16/2010,Not Specified,30,4684.9000,0.01,Delivery Truck,-549.27,150.98,...,Northwest Territories,Corporate,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,1/19/2010,high,high
230,3666,26272,6/29/2012,Low,6,905.9400,0.04,Express Air,-4.19,140.81,...,Northwest Territories,Home Office,Furniture,Chairs & Chairmats,Hon Olson Stacker Stools,Large Box,0.57,7/8/2012,high,high
231,3688,26370,8/8/2011,Not Specified,12,270.2300,0.08,Regular Air,52.02,22.84,...,Northwest Territories,Home Office,Office Supplies,Paper,Xerox 1929,Small Box,0.39,8/10/2011,low,low

Convert Region and Product Category to category dtype and compare memory before/
after with df.memory_usage(deep=True)

In [14]:
print(df.info())
df['Region'], df['Product Category'] = df['Region'].astype('category'), df['Product Category'].astype('category')
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                232 non-null    int64
 1   Order ID              232 non-null    int64
 2   Order Date            232 non-null    str
 3   Order Priority        232 non-null    str
 4   Order Quantity        232 non-null    int64
 5   Sales                 232 non-null    float64
 6   Discount              232 non-null    float64
 7   Ship Mode             232 non-null    str
 8   Profit                232 non-null    float64
 9   Unit Price            232 non-null    float64
 10  Shipping Cost         232 non-null    float64
 11  Customer Name         232 non-null    str
 12  Province              232 non-null    str
 13  Region                232 non-null    str
 14  Customer Segment      232 non-null    str
 15  Product Category      232 non-null    str
 16  Product Sub-Category  232 non-null    str
 17  Product Name          232 non-null    str
 18  Product Container     232 non-null    str
 19  Product Base Margin   228 non-null    float64
 20  Ship Date             232 non-null    str
dtypes: float64(6), int64(3), str(12)
memory usage: 75.8 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                232 non-null    int64
 1   Order ID              232 non-null    int64
 2   Order Date            232 non-null    str
 3   Order Priority        232 non-null    str
 4   Order Quantity        232 non-null    int64
 5   Sales                 232 non-null    float64
 6   Discount              232 non-null    float64
 7   Ship Mode             232 non-null    str
 8   Profit                232 non-null    float64
 9   Unit Price            232 non-null    float64
 10  Shipping Cost         232 non-null    float64
 11  Customer Name         232 non-null    str
 12  Province              232 non-null    str
 13  Region                232 non-null    category
 14  Customer Segment      232 non-null    str
 15  Product Category      232 non-null    category
 16  Product Sub-Category  232 non-null    str
 17  Product Name          232 non-null    str
 18  Product Container     232 non-null    str
 19  Product Base Margin   228 non-null    float64
 20  Ship Date             232 non-null    str
dtypes: category(2), float64(6), int64(3), str(10)
memory usage: 66.2 KB
None

Rewrite a multi-step transformation (add a month column, group, sort) as a single
method chain using assign .

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df = df.assign(
    month = df['Order Date'].dt.month_name(),
    group = df['Order Date'].dt.quarter,
    
)
df

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date,month,group,sort
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010,October,4,2010-10-13
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,10/2/2012,October,4,2012-10-01
2,50,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-Dï¿½ Ring Binder, Heavy Gauge V...",Small Box,0.39,10/3/2012,October,4,2012-10-01
3,80,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,7/12/2011,July,3,2011-07-10
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010,August,3,2010-08-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,3644,26051,2010-06-27,Not Specified,31,251.7500,0.07,Regular Air,22.46,8.33,...,Home Office,Technology,Computer Peripherals,"80 Minute Slim Jewel Case CD-R , 10/Pack - Sta...",Small Pack,0.52,6/28/2010,June,2,2010-06-27
228,3649,26116,2012-10-29,Critical,36,697.4100,0.04,Regular Air,81.71,18.97,...,Small Business,Office Supplies,Paper,Computer Printout Paper with Letter-Trim Perfo...,Small Box,0.37,10/30/2012,October,4,2012-10-29
229,3658,26182,2010-01-16,Not Specified,30,4684.9000,0.01,Delivery Truck,-549.27,150.98,...,Corporate,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,1/19/2010,January,1,2010-01-16
230,3666,26272,2012-06-29,Low,6,905.9400,0.04,Express Air,-4.19,140.81,...,Home Office,Furniture,Chairs & Chairmats,Hon Olson Stacker Stools,Large Box,0.57,7/8/2012,June,2,2012-06-29
231,3688,26370,2011-08-08,Not Specified,12,270.2300,0.08,Regular Air,52.02,22.84,...,Home Office,Office Supplies,Paper,Xerox 1929,Small Box,0.39,8/10/2011,August,3,2011-08-08