In [72]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    "Student ID": [101,102,103,104,104,106,107,108,109,110],
    "Name": [
        " Alice ",
        "Bob",
        "Charlie",
        "David",
        "David",
        "Emma",
        "Frank",
        "Grace",
        "Henry",
        np.nan
    ],
    "Age": [
        20,
        np.nan,
        22,
        -1,
        -1,
        21,
        23,
        20,
        np.nan,
        24
    ],
    "Gender": [
        " Male ",
        "female",
        "Female",
        "MALE",
        "MALE",
        "female",
        "Male",
        "Female",
        "male",
        " Female "
    ],
    "Department": [
        "Computer Science",
        "computer science",
        "IT",
        "Information Technology",
        "Information Technology",
        np.nan,
        "IT",
        "Computer Science",
        "IT",
        "Computer Science"
    ],
    "Marks": [
        85,
        90,
        np.nan,
        70,
        70,
        88,
        95,
        102,
        76,
        81
    ],
    "Enrollment Date": [
        "2024-01-10",
        "2024-01-12",
        "2024-02-01",
        "2024-01-20",
        "2024-01-20",
        "2024-03-05",
        "2024-03-12",
        "2024-02-15",
        "2024-02-20",
        "2024-03-01"
    ]
})

print(df)

   Student ID     Name   Age    Gender              Department  Marks  \
0         101   Alice   20.0     Male         Computer Science   85.0
1         102      Bob   NaN    female        computer science   90.0
2         103  Charlie  22.0    Female                      IT    NaN
3         104    David  -1.0      MALE  Information Technology   70.0
4         104    David  -1.0      MALE  Information Technology   70.0
5         106     Emma  21.0    female                     NaN   88.0
6         107    Frank  23.0      Male                      IT   95.0
7         108    Grace  20.0    Female        Computer Science  102.0
8         109    Henry   NaN      male                      IT   76.0
9         110      NaN  24.0   Female         Computer Science   81.0

  Enrollment Date
0      2024-01-10
1      2024-01-12
2      2024-02-01
3      2024-01-20
4      2024-01-20
5      2024-03-05
6      2024-03-12
7      2024-02-15
8      2024-02-20
9      2024-03-01

Task 4 — Boolean Filtering

Find students:

1. Older than 21.
2. Younger than 21.
3. Exactly 20 years old.
4. With marks above 80.
5. With marks below 75.
6. In the IT department.
7. In Computer Science.
8. With missing ages.
9. With missing names.
10. Whose marks are between 80 and 90.

In [73]:
print('question 1')
print(df[df['Age'] > 21])
print('question 2')
print(df[df['Age'] < 21])
print('question 3')
print(df[df['Age'] == 21])
print('question 4')
print(df[df['Marks'] > 80])
print('question 5')
print(df[df['Marks'] < 75])
print('question 6')
print(df[df['Department'] == 'IT'])
print('question 7')
df = df.replace('Computer Science', 'computer science')
print(df[df['Department'] == 'computer science'])
sf = df.dropna(subset=['Age'])
sf = df.dropna(subset=['Name'])
print(sf.query('80 < Marks and Marks < 90'))

question 1
   Student ID     Name   Age    Gender        Department  Marks  \
2         103  Charlie  22.0    Female                IT    NaN
6         107    Frank  23.0      Male                IT   95.0
9         110      NaN  24.0   Female   Computer Science   81.0

  Enrollment Date
2      2024-02-01
6      2024-03-12
9      2024-03-01
question 2
   Student ID     Name   Age  Gender              Department  Marks  \
0         101   Alice   20.0   Male         Computer Science   85.0
3         104    David  -1.0    MALE  Information Technology   70.0
4         104    David  -1.0    MALE  Information Technology   70.0
7         108    Grace  20.0  Female        Computer Science  102.0

  Enrollment Date
0      2024-01-10
3      2024-01-20
4      2024-01-20
7      2024-02-15
question 3
   Student ID  Name   Age  Gender Department  Marks Enrollment Date
5         106  Emma  21.0  female        NaN   88.0      2024-03-05
question 4
   Student ID     Name   Age    Gender        Department  Marks  \
0         101   Alice   20.0     Male   Computer Science   85.0
1         102      Bob   NaN    female  computer science   90.0
5         106     Emma  21.0    female               NaN   88.0
6         107    Frank  23.0      Male                IT   95.0
7         108    Grace  20.0    Female  Computer Science  102.0
9         110      NaN  24.0   Female   Computer Science   81.0

  Enrollment Date
0      2024-01-10
1      2024-01-12
5      2024-03-05
6      2024-03-12
7      2024-02-15
9      2024-03-01
question 5
   Student ID   Name  Age Gender              Department  Marks  \
3         104  David -1.0   MALE  Information Technology   70.0
4         104  David -1.0   MALE  Information Technology   70.0

  Enrollment Date
3      2024-01-20
4      2024-01-20
question 6
   Student ID     Name   Age  Gender Department  Marks Enrollment Date
2         103  Charlie  22.0  Female         IT    NaN      2024-02-01
6         107    Frank  23.0    Male         IT   95.0      2024-03-12
8         109    Henry   NaN    male         IT   76.0      2024-02-20
question 7
   Student ID     Name   Age    Gender        Department  Marks  \
0         101   Alice   20.0     Male   computer science   85.0
1         102      Bob   NaN    female  computer science   90.0
7         108    Grace  20.0    Female  computer science  102.0
9         110      NaN  24.0   Female   computer science   81.0

  Enrollment Date
0      2024-01-10
1      2024-01-12
7      2024-02-15
9      2024-03-01
   Student ID     Name   Age  Gender        Department  Marks Enrollment Date
0         101   Alice   20.0   Male   computer science   85.0      2024-01-10
5         106     Emma  21.0  female               NaN   88.0      2024-03-05

Task 5 — Multiple Conditions

Find students:

1. Older than 20 and marks above 80.
2. In IT and older than 21.
3. In IT or Computer Science.
4. Marks above 80 or age below 21.
5. Female students scoring above 80.

In [74]:
print('question 1')
print(df.query('Age > 20 and Marks > 80'))
print('question 2')
print(df.query("Age > 21 and Department == 'IT'"))
print('question 3')
print(df.query("Department == 'IT' or Department == 'computer science'"))
print('question 4')
print(df.query("Age < 21 or Marks > 80"))
print('question 5')
df = df.replace(['FEMALE', 'Female'], ['female', 'female'])
print(df.query("Gender == 'female' and Marks > 80"))
print(df)

question 1
   Student ID   Name   Age    Gender        Department  Marks Enrollment Date
5         106   Emma  21.0    female               NaN   88.0      2024-03-05
6         107  Frank  23.0      Male                IT   95.0      2024-03-12
9         110    NaN  24.0   Female   computer science   81.0      2024-03-01
question 2
   Student ID     Name   Age  Gender Department  Marks Enrollment Date
2         103  Charlie  22.0  Female         IT    NaN      2024-02-01
6         107    Frank  23.0    Male         IT   95.0      2024-03-12
question 3
   Student ID     Name   Age    Gender        Department  Marks  \
0         101   Alice   20.0     Male   computer science   85.0
1         102      Bob   NaN    female  computer science   90.0
2         103  Charlie  22.0    Female                IT    NaN
6         107    Frank  23.0      Male                IT   95.0
7         108    Grace  20.0    Female  computer science  102.0
8         109    Henry   NaN      male                IT   76.0
9         110      NaN  24.0   Female   computer science   81.0

  Enrollment Date
0      2024-01-10
1      2024-01-12
2      2024-02-01
6      2024-03-12
7      2024-02-15
8      2024-02-20
9      2024-03-01
question 4
   Student ID     Name   Age    Gender              Department  Marks  \
0         101   Alice   20.0     Male         computer science   85.0
1         102      Bob   NaN    female        computer science   90.0
3         104    David  -1.0      MALE  Information Technology   70.0
4         104    David  -1.0      MALE  Information Technology   70.0
5         106     Emma  21.0    female                     NaN   88.0
6         107    Frank  23.0      Male                      IT   95.0
7         108    Grace  20.0    Female        computer science  102.0
9         110      NaN  24.0   Female         computer science   81.0

  Enrollment Date
0      2024-01-10
1      2024-01-12
3      2024-01-20
4      2024-01-20
5      2024-03-05
6      2024-03-12
7      2024-02-15
9      2024-03-01
question 5
   Student ID   Name   Age  Gender        Department  Marks Enrollment Date
1         102    Bob   NaN  female  computer science   90.0      2024-01-12
5         106   Emma  21.0  female               NaN   88.0      2024-03-05
7         108  Grace  20.0  female  computer science  102.0      2024-02-15
   Student ID     Name   Age    Gender              Department  Marks  \
0         101   Alice   20.0     Male         computer science   85.0
1         102      Bob   NaN    female        computer science   90.0
2         103  Charlie  22.0    female                      IT    NaN
3         104    David  -1.0      MALE  Information Technology   70.0
4         104    David  -1.0      MALE  Information Technology   70.0
5         106     Emma  21.0    female                     NaN   88.0
6         107    Frank  23.0      Male                      IT   95.0
7         108    Grace  20.0    female        computer science  102.0
8         109    Henry   NaN      male                      IT   76.0
9         110      NaN  24.0   Female         computer science   81.0

  Enrollment Date
0      2024-01-10
1      2024-01-12
2      2024-02-01
3      2024-01-20
4      2024-01-20
5      2024-03-05
6      2024-03-12
7      2024-02-15
8      2024-02-20
9      2024-03-01

Task 6 wants repeat which i wont add here for brevity

Task 7 — Investigate Missing Data

Answer:

1. How many missing values are in each column?
2. Which column has the most missing values?
3. Which rows contain missing data?

In [75]:
print(df.isnull().sum())
print(df[df.isnull().any(axis=1)])

Student ID         0
Name               1
Age                2
Gender             0
Department         1
Marks              1
Enrollment Date    0
dtype: int64
   Student ID     Name   Age    Gender        Department  Marks  \
1         102      Bob   NaN    female  computer science   90.0
2         103  Charlie  22.0    female                IT    NaN
5         106     Emma  21.0    female               NaN   88.0
8         109    Henry   NaN      male                IT   76.0
9         110      NaN  24.0   Female   computer science   81.0

  Enrollment Date
1      2024-01-12
2      2024-02-01
5      2024-03-05
8      2024-02-20
9      2024-03-01

Task 8 — Filling Missing Values

Fill:

1. Age using the median.
2. Marks using the mean.
3. Department with "Unknown".
4. Name with "Missing".

In [76]:
mf = df.copy()
mf['Age'] = mf['Age'].fillna(mf['Age'].median())
mf['Marks'] = mf['Marks'].fillna(mf['Marks'].mean())
mf['Department'] = mf['Department'].fillna('Unknown')
mf['Name'] = mf['Name'].fillna('Missing')
print(mf)

   Student ID     Name   Age    Gender              Department       Marks  \
0         101   Alice   20.0     Male         computer science   85.000000
1         102      Bob  20.5    female        computer science   90.000000
2         103  Charlie  22.0    female                      IT   84.111111
3         104    David  -1.0      MALE  Information Technology   70.000000
4         104    David  -1.0      MALE  Information Technology   70.000000
5         106     Emma  21.0    female                 Unknown   88.000000
6         107    Frank  23.0      Male                      IT   95.000000
7         108    Grace  20.0    female        computer science  102.000000
8         109    Henry  20.5      male                      IT   76.000000
9         110  Missing  24.0   Female         computer science   81.000000

  Enrollment Date
0      2024-01-10
1      2024-01-12
2      2024-02-01
3      2024-01-20
4      2024-01-20
5      2024-03-05
6      2024-03-12
7      2024-02-15
8      2024-02-20
9      2024-03-01

Task 9 — Dropping Missing Values

Create new DataFrames:

1. Drop every row containing missing values.
2. Drop only rows missing Name.
3. Drop only rows missing Department.
4. Drop columns containing missing values.

In [77]:
drop_df = df.copy()
ddf = df.copy()
drop_df = drop_df.dropna()
ddf = ddf.dropna(subset=['Name'])
ddf = ddf.dropna(subset=['Department'])
ddf = ddf.dropna(axis=1)
print(ddf)

   Student ID     Name  Gender              Department Enrollment Date
0         101   Alice    Male         computer science      2024-01-10
1         102      Bob  female        computer science      2024-01-12
2         103  Charlie  female                      IT      2024-02-01
3         104    David    MALE  Information Technology      2024-01-20
4         104    David    MALE  Information Technology      2024-01-20
6         107    Frank    Male                      IT      2024-03-12
7         108    Grace  female        computer science      2024-02-15
8         109    Henry    male                      IT      2024-02-20

Task 11 — Invalid Values

Find:

1. Students with negative ages.
2. Students whose marks exceed 100.
3. Students whose marks are below 0.
4. Replace negative ages with NaN.
5. Replace marks above 100 with NaN.

In [78]:
# print(df.query("Age < 0"))
# print(df.query("Marks > 100"))
# print(df.query("Marks < 0"))
df = df.replace(np.nan, 0)
df["Age"] = np.where(df["Age"] < 0, np.nan, df["Age"])
df["Marks"] = np.where(df["Marks"] > 100, np.nan, df["Marks"])
print(df)

   Student ID     Name   Age    Gender              Department  Marks  \
0         101   Alice   20.0     Male         computer science   85.0
1         102      Bob   0.0    female        computer science   90.0
2         103  Charlie  22.0    female                      IT    0.0
3         104    David   NaN      MALE  Information Technology   70.0
4         104    David   NaN      MALE  Information Technology   70.0
5         106     Emma  21.0    female                       0   88.0
6         107    Frank  23.0      Male                      IT   95.0
7         108    Grace  20.0    female        computer science    NaN
8         109    Henry   0.0      male                      IT   76.0
9         110        0  24.0   Female         computer science   81.0

  Enrollment Date
0      2024-01-10
1      2024-01-12
2      2024-02-01
3      2024-01-20
4      2024-01-20
5      2024-03-05
6      2024-03-12
7      2024-02-15
8      2024-02-20
9      2024-03-01

Task 12 — Text Cleaning

Clean the Gender column so every value becomes either:

male
female

Clean the Name column by removing spaces.

Clean the Department column so:

Computer Science
computer science

become

Computer Science

and

Information Technology
IT

become

IT

In [79]:
df["Gender"]=df["Gender"].str.strip().str.lower()
df["Name"]=df["Name"].str.strip()
df["Department"]=np.where(df["Department"].str.strip().str.replace(" ", "").str.lower() == "computerscience", df["Department"].str.title(), df["Department"])
df["Department"]=np.where(df["Department"].str.strip().str.replace(" ", "").str.lower()=="informationtechnology", 'IT', df["Department"])
print(df)

   Student ID     Name   Age  Gender        Department  Marks Enrollment Date
0         101    Alice  20.0    male  Computer Science   85.0      2024-01-10
1         102      Bob   0.0  female  Computer Science   90.0      2024-01-12
2         103  Charlie  22.0  female                IT    0.0      2024-02-01
3         104    David   NaN    male                IT   70.0      2024-01-20
4         104    David   NaN    male                IT   70.0      2024-01-20
5         106     Emma  21.0  female                 0   88.0      2024-03-05
6         107    Frank  23.0    male                IT   95.0      2024-03-12
7         108    Grace  20.0  female  Computer Science    NaN      2024-02-15
8         109    Henry   0.0    male                IT   76.0      2024-02-20
9         110      NaN  24.0  female  Computer Science   81.0      2024-03-01

Task 13 — Datatypes
1. Display current datatypes.
2. Convert Enrollment Date to datetime.
3. Extract:
Year
Month
Day
Day name

into new columns.

In [80]:
df.info()
df["Enrollment Date"] = pd.to_datetime(df["Enrollment Date"])
df["year"]=df["Enrollment Date"].dt.year
df["Month"]=df["Enrollment Date"].dt.month
df["day"]=df["Enrollment Date"].dt.day
df["day name"]=df["Enrollment Date"].dt.day_name()
print(df)

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student ID       10 non-null     int64
 1   Name             9 non-null      object
 2   Age              8 non-null      float64
 3   Gender           10 non-null     str
 4   Department       10 non-null     object
 5   Marks            9 non-null      float64
 6   Enrollment Date  10 non-null     str
dtypes: float64(2), int64(1), object(2), str(2)
memory usage: 692.0+ bytes
   Student ID     Name   Age  Gender        Department  Marks Enrollment Date  \
0         101    Alice  20.0    male  Computer Science   85.0      2024-01-10
1         102      Bob   0.0  female  Computer Science   90.0      2024-01-12
2         103  Charlie  22.0  female                IT    0.0      2024-02-01
3         104    David   NaN    male                IT   70.0      2024-01-20
4         104    David   NaN    male                IT   70.0      2024-01-20
5         106     Emma  21.0  female                 0   88.0      2024-03-05
6         107    Frank  23.0    male                IT   95.0      2024-03-12
7         108    Grace  20.0  female  Computer Science    NaN      2024-02-15
8         109    Henry   0.0    male                IT   76.0      2024-02-20
9         110      NaN  24.0  female  Computer Science   81.0      2024-03-01

   year  Month  day   day name
0  2024      1   10  Wednesday
1  2024      1   12     Friday
2  2024      2    1   Thursday
3  2024      1   20   Saturday
4  2024      1   20   Saturday
5  2024      3    5    Tuesday
6  2024      3   12    Tuesday
7  2024      2   15   Thursday
8  2024      2   20    Tuesday
9  2024      3    1     Friday

Task 14 — Renaming Columns

Rename:

Student ID

to

student_id

Rename

Enrollment Date

to

enrollment_date

Rename

Computer Science

In [81]:
df.rename(columns={"Student ID":"student_id", "Enrollment Date": "enrollment_date"}, inplace = True)
df["Department"]=np.where(df["Department"]=="Computer Science", "computer_science", df["Department"])
print(df)

   student_id     Name   Age  Gender        Department  Marks enrollment_date  \
0         101    Alice  20.0    male  computer_science   85.0      2024-01-10
1         102      Bob   0.0  female  computer_science   90.0      2024-01-12
2         103  Charlie  22.0  female                IT    0.0      2024-02-01
3         104    David   NaN    male                IT   70.0      2024-01-20
4         104    David   NaN    male                IT   70.0      2024-01-20
5         106     Emma  21.0  female                 0   88.0      2024-03-05
6         107    Frank  23.0    male                IT   95.0      2024-03-12
7         108    Grace  20.0  female  computer_science    NaN      2024-02-15
8         109    Henry   0.0    male                IT   76.0      2024-02-20
9         110      NaN  24.0  female  computer_science   81.0      2024-03-01

   year  Month  day   day name
0  2024      1   10  Wednesday
1  2024      1   12     Friday
2  2024      2    1   Thursday
3  2024      1   20   Saturday
4  2024      1   20   Saturday
5  2024      3    5    Tuesday
6  2024      3   12    Tuesday
7  2024      2   15   Thursday
8  2024      2   20    Tuesday
9  2024      3    1     Friday

Task 15 — Final Validation

After cleaning:

Run

1. df.info()
2. .df.describe()
3. df.isnull().sum()
4. df.duplicated().sum()
5. df["Department"].value_counts()

Check whether:

There are no duplicate rows.
Invalid ages have been handled.
Marks greater than 100 have been handled.
Text values are consistent.
Dates are real datetime objects.
Missing values have been addressed according to your chosen strategy.

In [82]:
df.info()
df.describe()
df=df.dropna()
print(df.isnull().sum())
df=df.drop_duplicates()
print(df.duplicated().sum())
df["Department"]=np.where((df["Department"]).str.replace(" ", "") == "informationtechnology", "IT", df["Department"])
print(df["Department"].value_counts())
print(df)

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_id       10 non-null     int64
 1   Name             9 non-null      object
 2   Age              8 non-null      float64
 3   Gender           10 non-null     str
 4   Department       10 non-null     object
 5   Marks            9 non-null      float64
 6   enrollment_date  10 non-null     datetime64[us]
 7   year             10 non-null     int32
 8   Month            10 non-null     int32
 9   day              10 non-null     int32
 10  day name         10 non-null     str
dtypes: datetime64[us](1), float64(2), int32(3), int64(1), object(2), str(2)
memory usage: 892.0+ bytes
student_id         0
Name               0
Age                0
Gender             0
Department         0
Marks              0
enrollment_date    0
year               0
Month              0
day                0
day name           0
dtype: int64
0
Department
IT                  3
computer_science    2
0                   1
Name: count, dtype: int64
   student_id     Name   Age  Gender        Department  Marks enrollment_date  \
0         101    Alice  20.0    male  computer_science   85.0      2024-01-10
1         102      Bob   0.0  female  computer_science   90.0      2024-01-12
2         103  Charlie  22.0  female                IT    0.0      2024-02-01
5         106     Emma  21.0  female                 0   88.0      2024-03-05
6         107    Frank  23.0    male                IT   95.0      2024-03-12
8         109    Henry   0.0    male                IT   76.0      2024-02-20

   year  Month  day   day name
0  2024      1   10  Wednesday
1  2024      1   12     Friday
2  2024      2    1   Thursday
5  2024      3    5    Tuesday
6  2024      3   12    Tuesday
8  2024      2   20    Tuesday

Tasks for module 8 and 9

In [83]:
import pandas as pd
import numpy as np

sales = pd.DataFrame({
    "OrderID":[101,102,103,104,105,106,107,108,109,110],
    "CustomerID":[1,2,1,3,2,4,3,5,4,1],
    "Region":["East","West","East","North","West","South","North","East","South","East"],
    "Category":["Laptop","Mouse","Keyboard","Laptop","Mouse","Monitor","Laptop","Keyboard","Monitor","Mouse"],
    "Price":[900,25,60,850,25,300,920,70,310,30],
    "Quantity":[1,4,2,1,5,2,1,3,1,6]
})
customers = pd.DataFrame({
    "CustomerID":[1,2,3,4,5],
    "CustomerName":["Alice","Bob","Charlie","David","Emma"],
    "Membership":["Gold","Silver","Gold","Bronze","Silver"]
})

task1
Create a new column called

Total

Formula

Price × Quantity

In [84]:
sales['total']= sales['Price']* sales['Quantity']
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total
0      101           1   East    Laptop    900         1    900
1      102           2   West     Mouse     25         4    100
2      103           1   East  Keyboard     60         2    120
3      104           3  North    Laptop    850         1    850
4      105           2   West     Mouse     25         5    125
5      106           4  South   Monitor    300         2    600
6      107           3  North    Laptop    920         1    920
7      108           5   East  Keyboard     70         3    210
8      109           4  South   Monitor    310         1    310
9      110           1   East     Mouse     30         6    180

Task2 Increase every product price by 8%.

Overwrite the original Price column.

In [85]:
sales['Price']= sales['Price'] * 1.08
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total
0      101           1   East    Laptop  972.0         1    900
1      102           2   West     Mouse   27.0         4    100
2      103           1   East  Keyboard   64.8         2    120
3      104           3  North    Laptop  918.0         1    850
4      105           2   West     Mouse   27.0         5    125
5      106           4  South   Monitor  324.0         2    600
6      107           3  North    Laptop  993.6         1    920
7      108           5   East  Keyboard   75.6         3    210
8      109           4  South   Monitor  334.8         1    310
9      110           1   East     Mouse   32.4         6    180

task 3 Create a column called

Tax

which is

10% of Total

In [86]:
sales['tax']= sales['Price'] * .1
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax
0      101           1   East    Laptop  972.0         1    900  97.20
1      102           2   West     Mouse   27.0         4    100   2.70
2      103           1   East  Keyboard   64.8         2    120   6.48
3      104           3  North    Laptop  918.0         1    850  91.80
4      105           2   West     Mouse   27.0         5    125   2.70
5      106           4  South   Monitor  324.0         2    600  32.40
6      107           3  North    Laptop  993.6         1    920  99.36
7      108           5   East  Keyboard   75.6         3    210   7.56
8      109           4  South   Monitor  334.8         1    310  33.48
9      110           1   East     Mouse   32.4         6    180   3.24

task 4 Create a column

FinalPrice

Formula

Total + Tax

In [87]:
sales['final_price'] = sales['total'] + sales['tax']
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
0      101           1   East    Laptop  972.0         1    900  97.20
1      102           2   West     Mouse   27.0         4    100   2.70
2      103           1   East  Keyboard   64.8         2    120   6.48
3      104           3  North    Laptop  918.0         1    850  91.80
4      105           2   West     Mouse   27.0         5    125   2.70
5      106           4  South   Monitor  324.0         2    600  32.40
6      107           3  North    Laptop  993.6         1    920  99.36
7      108           5   East  Keyboard   75.6         3    210   7.56
8      109           4  South   Monitor  334.8         1    310  33.48
9      110           1   East     Mouse   32.4         6    180   3.24

   final_price
0       997.20
1       102.70
2       126.48
3       941.80
4       127.70
5       632.40
6      1019.36
7       217.56
8       343.48
9       183.24

Task 5 (apply)

Create a function that labels each order.

Rules

Total >= 1500 → Large

500–1499 → Medium

Below 500 → Small

Store in

OrderSize

In [88]:
sales['final_price'] = sales['total'] + sales['tax']
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
0      101           1   East    Laptop  972.0         1    900  97.20
1      102           2   West     Mouse   27.0         4    100   2.70
2      103           1   East  Keyboard   64.8         2    120   6.48
3      104           3  North    Laptop  918.0         1    850  91.80
4      105           2   West     Mouse   27.0         5    125   2.70
5      106           4  South   Monitor  324.0         2    600  32.40
6      107           3  North    Laptop  993.6         1    920  99.36
7      108           5   East  Keyboard   75.6         3    210   7.56
8      109           4  South   Monitor  334.8         1    310  33.48
9      110           1   East     Mouse   32.4         6    180   3.24

   final_price
0       997.20
1       102.70
2       126.48
3       941.80
4       127.70
5       632.40
6      1019.36
7       217.56
8       343.48
9       183.24

In [89]:
sales['order_size']= pd.cut(sales['total'], bins=[0,500,1500, float('inf')], labels=['small', 'med', 'large'])
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
0      101           1   East    Laptop  972.0         1    900  97.20
1      102           2   West     Mouse   27.0         4    100   2.70
2      103           1   East  Keyboard   64.8         2    120   6.48
3      104           3  North    Laptop  918.0         1    850  91.80
4      105           2   West     Mouse   27.0         5    125   2.70
5      106           4  South   Monitor  324.0         2    600  32.40
6      107           3  North    Laptop  993.6         1    920  99.36
7      108           5   East  Keyboard   75.6         3    210   7.56
8      109           4  South   Monitor  334.8         1    310  33.48
9      110           1   East     Mouse   32.4         6    180   3.24

   final_price order_size
0       997.20        med
1       102.70      small
2       126.48      small
3       941.80        med
4       127.70      small
5       632.40        med
6      1019.36        med
7       217.56      small
8       343.48      small
9       183.24      small

Task 6 

Create

HighValue

True if

Total > 1000

False otherwise.

In [90]:
sales['high_value']= np.where(sales['total'] > 1000, True, False)
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
0      101           1   East    Laptop  972.0         1    900  97.20
1      102           2   West     Mouse   27.0         4    100   2.70
2      103           1   East  Keyboard   64.8         2    120   6.48
3      104           3  North    Laptop  918.0         1    850  91.80
4      105           2   West     Mouse   27.0         5    125   2.70
5      106           4  South   Monitor  324.0         2    600  32.40
6      107           3  North    Laptop  993.6         1    920  99.36
7      108           5   East  Keyboard   75.6         3    210   7.56
8      109           4  South   Monitor  334.8         1    310  33.48
9      110           1   East     Mouse   32.4         6    180   3.24

   final_price order_size  high_value
0       997.20        med       False
1       102.70      small       False
2       126.48      small       False
3       941.80        med       False
4       127.70      small       False
5       632.40        med       False
6      1019.36        med       False
7       217.56      small       False
8       343.48      small       False
9       183.24      small       False

Create

BulkOrder

True when

Quantity >=5

In [91]:
sales['bulk_order'] = np.where(sales['Quantity'] > 5, True, False)
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
0      101           1   East    Laptop  972.0         1    900  97.20
1      102           2   West     Mouse   27.0         4    100   2.70
2      103           1   East  Keyboard   64.8         2    120   6.48
3      104           3  North    Laptop  918.0         1    850  91.80
4      105           2   West     Mouse   27.0         5    125   2.70
5      106           4  South   Monitor  324.0         2    600  32.40
6      107           3  North    Laptop  993.6         1    920  99.36
7      108           5   East  Keyboard   75.6         3    210   7.56
8      109           4  South   Monitor  334.8         1    310  33.48
9      110           1   East     Mouse   32.4         6    180   3.24

   final_price order_size  high_value  bulk_order
0       997.20        med       False       False
1       102.70      small       False       False
2       126.48      small       False       False
3       941.80        med       False       False
4       127.70      small       False       False
5       632.40        med       False       False
6      1019.36        med       False       False
7       217.56      small       False       False
8       343.48      small       False       False
9       183.24      small       False        True

Part B — Sorting
Task 8

Sort by

Total

largest first.

In [92]:
sales = sales.sort_values(by='total', ascending=False)
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
6      107           3  North    Laptop  993.6         1    920  99.36
0      101           1   East    Laptop  972.0         1    900  97.20
3      104           3  North    Laptop  918.0         1    850  91.80
5      106           4  South   Monitor  324.0         2    600  32.40
8      109           4  South   Monitor  334.8         1    310  33.48
7      108           5   East  Keyboard   75.6         3    210   7.56
9      110           1   East     Mouse   32.4         6    180   3.24
4      105           2   West     Mouse   27.0         5    125   2.70
2      103           1   East  Keyboard   64.8         2    120   6.48
1      102           2   West     Mouse   27.0         4    100   2.70

   final_price order_size  high_value  bulk_order
6      1019.36        med       False       False
0       997.20        med       False       False
3       941.80        med       False       False
5       632.40        med       False       False
8       343.48      small       False       False
7       217.56      small       False       False
9       183.24      small       False        True
4       127.70      small       False       False
2       126.48      small       False       False
1       102.70      small       False       False

Task 9

Sort by

Region (A-Z)

then

Total (largest first)

In [93]:
sales = sales.sort_values(by=['Region', 'total'], ascending=[True, False])
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
0      101           1   East    Laptop  972.0         1    900  97.20
7      108           5   East  Keyboard   75.6         3    210   7.56
9      110           1   East     Mouse   32.4         6    180   3.24
2      103           1   East  Keyboard   64.8         2    120   6.48
6      107           3  North    Laptop  993.6         1    920  99.36
3      104           3  North    Laptop  918.0         1    850  91.80
5      106           4  South   Monitor  324.0         2    600  32.40
8      109           4  South   Monitor  334.8         1    310  33.48
4      105           2   West     Mouse   27.0         5    125   2.70
1      102           2   West     Mouse   27.0         4    100   2.70

   final_price order_size  high_value  bulk_order
0       997.20        med       False       False
7       217.56      small       False       False
9       183.24      small       False        True
2       126.48      small       False       False
6      1019.36        med       False       False
3       941.80        med       False       False
5       632.40        med       False       False
8       343.48      small       False       False
4       127.70      small       False       False
1       102.70      small       False       False

Task 10

Find the three most expensive products after the price increase.

In [94]:
sales = sales.sort_values(by='Price', ascending=False)
print(sales.head(3))

   OrderID  CustomerID Region Category  Price  Quantity  total    tax  \
6      107           3  North   Laptop  993.6         1    920  99.36
0      101           1   East   Laptop  972.0         1    900  97.20
3      104           3  North   Laptop  918.0         1    850  91.80

   final_price order_size  high_value  bulk_order
6      1019.36        med       False       False
0       997.20        med       False       False
3       941.80        med       False       False

Part C — GroupBy
Task 11

Calculate total sales (Total) by Region.

In [95]:
sales.groupby('Region')['total'].sum()

Region
East     1410
North    1770
South     910
West      225
Name: total, dtype: int64

Task 12

Find average Total by Category.

In [96]:
sales.groupby('Category')['total'].mean()

Category
Keyboard    165.0
Laptop      890.0
Monitor     455.0
Mouse       135.0
Name: total, dtype: float64

Task 13

Find

sum

mean

count

max

min

for Total grouped by Region

In [97]:
sales.groupby('Region')['total'].agg(['sum', 'mean', 'count', 'max', 'min'])

         sum   mean  count  max  min
Region
East    1410  352.5      4  900  120
North   1770  885.0      2  920  850
South    910  455.0      2  600  310
West     225  112.5      2  125  100

Task 14

Calculate total quantity sold for each Category.

In [98]:
sales.groupby('Category')['Quantity'].sum()

Category
Keyboard     5
Laptop       3
Monitor      3
Mouse       15
Name: Quantity, dtype: int64

Task 15

Find which customer spent the most.

(Hint: group by CustomerID.)

In [99]:
sales.groupby('CustomerID')['total'].sum()

CustomerID
1    1200
2     225
3    1770
4     910
5     210
Name: total, dtype: int64

Part D — Value Counts
Task 16

Count how many orders came from each Region.

In [100]:
sales.groupby('Region')['Quantity'].sum()

Region
East     12
North     2
South     3
West      9
Name: Quantity, dtype: int64

Task 17

Find the two most common Categories.

In [101]:
t2 = sales['Category'].value_counts().head(2)
print(t2)

Category
Laptop    3
Mouse     3
Name: count, dtype: int64

Task 18

Show Region percentages instead of counts.

(Hint: normalize=True.)

In [102]:
sales.groupby('Region').value_counts(normalize=True)

Region  OrderID  CustomerID  Category  Price  Quantity  total  tax    final_price  order_size  high_value  bulk_order
East    101      1           Laptop    972.0  1         900    97.20  997.20       med         False       False         0.25
        108      5           Keyboard  75.6   3         210    7.56   217.56       small       False       False         0.25
        103      1           Keyboard  64.8   2         120    6.48   126.48       small       False       False         0.25
        110      1           Mouse     32.4   6         180    3.24   183.24       small       False       True          0.25
        101      1           Laptop    972.0  1         900    97.20  997.20       small       False       False         0.00
                                                                                   large       False       False         0.00
        108      5           Keyboard  75.6   3         210    7.56   217.56       med         False       False         0.00
                                                                                   large       False       False         0.00
        103      1           Keyboard  64.8   2         120    6.48   126.48       med         False       False         0.00
                                                                                   large       False       False         0.00
        110      1           Mouse     32.4   6         180    3.24   183.24       med         False       True          0.00
                                                                                   large       False       True          0.00
North   104      3           Laptop    918.0  1         850    91.80  941.80       med         False       False         0.50
        107      3           Laptop    993.6  1         920    99.36  1019.36      med         False       False         0.50
        104      3           Laptop    918.0  1         850    91.80  941.80       large       False       False         0.00
                                                                                   small       False       False         0.00
        107      3           Laptop    993.6  1         920    99.36  1019.36      large       False       False         0.00
                                                                                   small       False       False         0.00
South   109      4           Monitor   334.8  1         310    33.48  343.48       small       False       False         0.50
        106      4           Monitor   324.0  2         600    32.40  632.40       med         False       False         0.50
        109      4           Monitor   334.8  1         310    33.48  343.48       med         False       False         0.00
                                                                                   large       False       False         0.00
        106      4           Monitor   324.0  2         600    32.40  632.40       small       False       False         0.00
                                                                                   large       False       False         0.00
West    105      2           Mouse     27.0   5         125    2.70   127.70       small       False       False         0.50
        102      2           Mouse     27.0   4         100    2.70   102.70       small       False       False         0.50
        105      2           Mouse     27.0   5         125    2.70   127.70       med         False       False         0.00
                                                                                   large       False       False         0.00
        102      2           Mouse     27.0   4         100    2.70   102.70       med         False       False         0.00
                                                                                   large       False       False         0.00
Name: proportion, dtype: float64

Part E — Binning
Task 19 and 20

Create a column called

SalesLevel

Rules

0–500

Low

500–1500

Medium

1500+

High

Use pd.cut() (not apply()).

In [103]:
sales['sales_level'] = pd.cut(sales['Price'], bins=[0, 500, 1500, float('inf')], labels=['small', 'med', 'large'])
print(sales)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
6      107           3  North    Laptop  993.6         1    920  99.36
0      101           1   East    Laptop  972.0         1    900  97.20
3      104           3  North    Laptop  918.0         1    850  91.80
8      109           4  South   Monitor  334.8         1    310  33.48
5      106           4  South   Monitor  324.0         2    600  32.40
7      108           5   East  Keyboard   75.6         3    210   7.56
2      103           1   East  Keyboard   64.8         2    120   6.48
9      110           1   East     Mouse   32.4         6    180   3.24
4      105           2   West     Mouse   27.0         5    125   2.70
1      102           2   West     Mouse   27.0         4    100   2.70

   final_price order_size  high_value  bulk_order sales_level
6      1019.36        med       False       False         med
0       997.20        med       False       False         med
3       941.80        med       False       False         med
8       343.48      small       False       False       small
5       632.40        med       False       False       small
7       217.56      small       False       False       small
2       126.48      small       False       False       small
9       183.24      small       False        True       small
4       127.70      small       False       False       small
1       102.70      small       False       False       small

Part F — Merge (Module 9)
Task 21

Merge the sales table with customers using

CustomerID

Store the result as

merged

In [108]:
merged = pd.merge(sales, customers, on='CustomerID', how='outer')
print(merged)

   OrderID  CustomerID Region  Category  Price  Quantity  total    tax  \
0      101           1   East    Laptop  972.0         1    900  97.20
1      103           1   East  Keyboard   64.8         2    120   6.48
2      110           1   East     Mouse   32.4         6    180   3.24
3      105           2   West     Mouse   27.0         5    125   2.70
4      102           2   West     Mouse   27.0         4    100   2.70
5      107           3  North    Laptop  993.6         1    920  99.36
6      104           3  North    Laptop  918.0         1    850  91.80
7      109           4  South   Monitor  334.8         1    310  33.48
8      106           4  South   Monitor  324.0         2    600  32.40
9      108           5   East  Keyboard   75.6         3    210   7.56

   final_price order_size  high_value  bulk_order sales_level CustomerName  \
0       997.20        med       False       False         med        Alice
1       126.48      small       False       False       small        Alice
2       183.24      small       False        True       small        Alice
3       127.70      small       False       False       small          Bob
4       102.70      small       False       False       small          Bob
5      1019.36        med       False       False         med      Charlie
6       941.80        med       False       False         med      Charlie
7       343.48      small       False       False       small        David
8       632.40        med       False       False       small        David
9       217.56      small       False       False       small         Emma

  Membership
0       Gold
1       Gold
2       Gold
3     Silver
4     Silver
5       Gold
6       Gold
7     Bronze
8     Bronze
9     Silver

Task 22

Display

CustomerName

Category

Total

from the merged table.

In [107]:
print(merged[['CustomerName', 'Category', 'total']])

  CustomerName  Category  total
0        Alice    Laptop    900
1        Alice  Keyboard    120
2        Alice     Mouse    180
3          Bob     Mouse    125
4          Bob     Mouse    100
5      Charlie    Laptop    920
6      Charlie    Laptop    850
7        David   Monitor    310
8        David   Monitor    600
9         Emma  Keyboard    210

Task 23

Find total spending by Membership.

In [111]:
merged.groupby('Membership')['total'].sum()

Membership
Bronze     910
Gold      2970
Silver     435
Name: total, dtype: int64

Task 24

Find average spending by CustomerName.

In [113]:
merged.groupby('CustomerName')['total'].mean()

CustomerName
Alice      400.0
Bob        112.5
Charlie    885.0
David      455.0
Emma       210.0
Name: total, dtype: float64

In [114]:
new_sales = pd.DataFrame({
    "OrderID":[111,112],
    "CustomerID":[2,5],
    "Region":["West","East"],
    "Category":["Laptop","Monitor"],
    "Price":[950,320],
    "Quantity":[1,2]
})

Task 25

Append the new sales data onto the original sales table.

In [116]:
pd.concat([sales, new_sales], axis=1)

,OrderID,CustomerID,Region,Category,Price,Quantity,total,tax,final_price,order_size,high_value,bulk_order,sales_level,OrderID,CustomerID,Region,Category,Price,Quantity
6,107,3,North,Laptop,993.6,1,920,99.36,1019.36,med,False,False,med,NaN,NaN,NaN,NaN,NaN,NaN
0,101,1,East,Laptop,972.0,1,900,97.20,997.20,med,False,False,med,111.0,2.0,West,Laptop,950.0,1.0
3,104,3,North,Laptop,918.0,1,850,91.80,941.80,med,False,False,med,NaN,NaN,NaN,NaN,NaN,NaN
8,109,4,South,Monitor,334.8,1,310,33.48,343.48,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
5,106,4,South,Monitor,324.0,2,600,32.40,632.40,med,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
7,108,5,East,Keyboard,75.6,3,210,7.56,217.56,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
2,103,1,East,Keyboard,64.8,2,120,6.48,126.48,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
9,110,1,East,Mouse,32.4,6,180,3.24,183.24,small,False,True,small,NaN,NaN,NaN,NaN,NaN,NaN
4,105,2,West,Mouse,27.0,5,125,2.70,127.70,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
1,102,2,West,Mouse,27.0,4,100,2.70,102.70,small,False,False,small,112.0,5.0,East,Monitor,320.0,2.0

Task 26

Reset the index while concatenating.

In [117]:
pd.concat([sales, new_sales], axis=1, ignore_index=True)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
6,107,3,North,Laptop,993.6,1,920,99.36,1019.36,med,False,False,med,NaN,NaN,NaN,NaN,NaN,NaN
0,101,1,East,Laptop,972.0,1,900,97.20,997.20,med,False,False,med,111.0,2.0,West,Laptop,950.0,1.0
3,104,3,North,Laptop,918.0,1,850,91.80,941.80,med,False,False,med,NaN,NaN,NaN,NaN,NaN,NaN
8,109,4,South,Monitor,334.8,1,310,33.48,343.48,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
5,106,4,South,Monitor,324.0,2,600,32.40,632.40,med,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
7,108,5,East,Keyboard,75.6,3,210,7.56,217.56,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
2,103,1,East,Keyboard,64.8,2,120,6.48,126.48,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
9,110,1,East,Mouse,32.4,6,180,3.24,183.24,small,False,True,small,NaN,NaN,NaN,NaN,NaN,NaN
4,105,2,West,Mouse,27.0,5,125,2.70,127.70,small,False,False,small,NaN,NaN,NaN,NaN,NaN,NaN
1,102,2,West,Mouse,27.0,4,100,2.70,102.70,small,False,False,small,112.0,5.0,East,Monitor,320.0,2.0